import { Inter } from "next/font/google";
import "./globals.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className} class="bg-zinc-700">
        <Cabecalho />
        {children}
        </body>
    </html>
  );
}
